-- Operations Hub init: schemas + extensions
CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA IF NOT EXISTS gespack;
CREATE SCHEMA IF NOT EXISTS it;
CREATE SCHEMA IF NOT EXISTS auth;
