USE [MaylisPromovent]
GO

/****** Object:  Table [dbo].[Devoluciones]    Script Date: 02/11/2024 11:09:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Devoluciones](
	[FECHA] [date] NULL,
	[ACCION] [nvarchar](255) NULL,
	[NUMERO_DE_CLIENT] [nvarchar](255) NOT NULL,
	[MARCADO] [nvarchar](255) NULL,
 CONSTRAINT [PK_Devoluciones] PRIMARY KEY CLUSTERED 
(
	[NUMERO_DE_CLIENT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


