USE [MaylisPromovent]
GO

/****** Object:  Table [dbo].[Embalaje]    Script Date: 02/11/2024 11:09:42 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Embalaje](
	[TIPO_EMBALAJE] [nvarchar](255) NOT NULL,
	[Embalaje] [nvarchar](255) NULL,
	[Peso] [nvarchar](255) NULL,
	[DIMENSION] [nvarchar](255) NULL,
 CONSTRAINT [PK_Embalaje] PRIMARY KEY CLUSTERED 
(
	[TIPO_EMBALAJE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


