USE [MaylisPromovent_TEST]
GO

/****** Object:  Table [dbo].[ErrorLog]    Script Date: 09/03/2025 15:36:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ErrorLog](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FECHA] [datetime] NULL,
	[PEDIDO] [nvarchar](255) NULL,
	[DESCRIPCION] [nvarchar](255) NULL,
	[SECCION] [nvarchar](255) NULL,
	[USUARIO] [nvarchar](255) NULL,
	[GRABADO] [bit] NOT NULL,
	[MODIFICADO] [bit] NOT NULL,
	[FACTURADO] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ErrorLog] ADD  DEFAULT ((0)) FOR [GRABADO]
GO

ALTER TABLE [dbo].[ErrorLog] ADD  DEFAULT ((0)) FOR [MODIFICADO]
GO

ALTER TABLE [dbo].[ErrorLog] ADD  DEFAULT ((0)) FOR [FACTURADO]
GO


