USE [MaylisPromovent]
GO

/****** Object:  Table [dbo].[IVA_Anual]    Script Date: 02/11/2024 11:11:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[IVA_Anual](
	[Tipo_IVA] [nvarchar](255) NOT NULL,
	[IVA] [nvarchar](255) NULL,
	[PORCENTAJE] [nvarchar](255) NULL,
	[DESCRIPCION] [nvarchar](255) NULL,
 CONSTRAINT [PK_IVA_Anual] PRIMARY KEY CLUSTERED 
(
	[Tipo_IVA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


