USE [MaylisPromovent]
GO

/****** Object:  Table [dbo].[Montant]    Script Date: 02/11/2024 11:12:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Montant](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DESDE] [float] NULL,
	[HASTA] [float] NULL,
	[MONTANT] [float] NULL,
 CONSTRAINT [PK__Montant__3214EC27BF9C6571] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


