USE [MaylisPromovent]
GO

/****** Object:  Table [dbo].[Recencia]    Script Date: 02/11/2024 11:13:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Recencia](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DESDE] [nvarchar](255) NULL,
	[HASTA] [nvarchar](255) NULL,
	[RECENCIA] [nvarchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


