USE [MaylisPromovent]
GO

/****** Object:  Table [dbo].[Stock]    Script Date: 02/11/2024 11:14:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Stock](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[REFERENCIA] [nvarchar](50) NULL,
	[DESCRIPCION] [nvarchar](255) NULL,
	[CANTIDAD] [nvarchar](255) NULL,
	[ALBARAN_FACTURA] [nvarchar](255) NULL,
	[PROVEEDOR] [nvarchar](255) NULL,
	[FECHA_ENTRADA] [nvarchar](255) NULL,
	[TRABAJADOR] [nvarchar](255) NULL,
	[TIPO_ENTRADA] [nvarchar](255) NULL,
 CONSTRAINT [PK_Stock_1] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


