# Etapa 1: build de la app
FROM node:23-slim AS build

WORKDIR /app
RUN npm install -g pnpm
COPY package*.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile
COPY . .
RUN pnpm run build

# Etapa 2: servir con NGINX
FROM nginx:stable-alpine

# Copiar el build al directorio de NGINX
COPY --from=build /app/dist /usr/share/nginx/html

# ✅ Asignar permisos correctos (para evitar 403)
RUN chmod -R 644 /usr/share/nginx/html && \
    find /usr/share/nginx/html -type d -exec chmod 755 {} \;

# Elimina configuración por defecto de NGINX (opcional)
RUN rm /etc/nginx/conf.d/default.conf

# Añade configuración personalizada para SPA
COPY nginx.conf /etc/nginx/conf.d

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]