USE [GesPackAdmin]
GO

/****** Object:  Table [dbo].[Customers]    Script Date: 02/11/2024 11:16:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Customers](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CUST_NAME] [nvarchar](255) NOT NULL,
	[CUST_DESC] [nvarchar](255) NULL,
	[CUST_DATE] [nvarchar](255) NOT NULL,
	[CUST_BD] [nvarchar](255) NOT NULL,
	[LAST_UPDATE] [date] NULL,
	[CUST_NAME_WMS] [nvarchar](255) NOT NULL,
	[IS_ACTIVE] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Customers] ADD  DEFAULT ((1)) FOR [IS_ACTIVE]
GO


