USE [GesPackAdmin]
GO

/****** Object:  Table [dbo].[ImportFiles]    Script Date: 02/11/2024 11:16:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ImportFiles](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[IMP_NAME] [nvarchar](255) NULL,
	[IMP_DESCRIPTION] [nvarchar](255) NULL,
	[IMP_DATE] [date] NULL,
	[ID_NAME] [nvarchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


