USE [GesPackAdmin]
GO

/****** Object:  Table [dbo].[Users]    Script Date: 02/11/2024 11:18:22 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Users](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USER_NAME] [nvarchar](255) NULL,
	[USER_PASSWORD] [nvarchar](255) NULL,
	[EMAIL] [nvarchar](255) NULL,
	[IS_CUSTOMER] [bit] NULL,
	[IS_ADMIN] [bit] NULL,
	[ACTIVE] [bit] NULL,
	[IS_CB] [bit] NULL,
	[IS_LIST] [bit] NULL,
	[BD_CUSTOMER] [nvarchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


